// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9Yu0molcornXFoFjPmkQC-ZTuBI22buI',
    appId: '1:759302088738:web:da6a3348d68463b26e827b',
    messagingSenderId: '759302088738',
    projectId: 'officesync-7e075',
    authDomain: 'officesync-7e075.firebaseapp.com',
    storageBucket: 'officesync-7e075.firebasestorage.app',
    measurementId: 'G-QP656VXYLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh2pTqRQ-g0D-rHB4ZdO3rWcf1BOSNyMc',
    appId: '1:759302088738:android:59262e4d8692484c6e827b',
    messagingSenderId: '759302088738',
    projectId: 'officesync-7e075',
    storageBucket: 'officesync-7e075.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBLKWRS7X0yRk1BWWLXjlJ32eG3q-EAb0',
    appId: '1:759302088738:ios:30bd666040c4f6d66e827b',
    messagingSenderId: '759302088738',
    projectId: 'officesync-7e075',
    storageBucket: 'officesync-7e075.firebasestorage.app',
    iosBundleId: 'com.example.officesync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBLKWRS7X0yRk1BWWLXjlJ32eG3q-EAb0',
    appId: '1:759302088738:ios:30bd666040c4f6d66e827b',
    messagingSenderId: '759302088738',
    projectId: 'officesync-7e075',
    storageBucket: 'officesync-7e075.firebasestorage.app',
    iosBundleId: 'com.example.officesync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9Yu0molcornXFoFjPmkQC-ZTuBI22buI',
    appId: '1:759302088738:web:9081d7a86a5852cc6e827b',
    messagingSenderId: '759302088738',
    projectId: 'officesync-7e075',
    authDomain: 'officesync-7e075.firebaseapp.com',
    storageBucket: 'officesync-7e075.firebasestorage.app',
    measurementId: 'G-4R4MZDJWSJ',
  );
}
